### ISSUE TITLE
Create project page V3

### ISSUE THREAD

**Issue by lasaeren** [SELab-2/OSOC-5#120]
- [x] Color picker for roles #123 #176 #131

- [x] Color editable through table #176

- [x] Change the requests (make skill is going to have a comment field) once the database changes #176

- [x] Response (notification) after requests based of success #176

- [x] skillStore to typescript #162 #176

- [x] create project.vue typescript support #162 #176
